ALTER TABLE articles ADD COLUMN views INTEGER NOT NULL DEFAULT 0;
ALTER TABLE articles ADD COLUMN likes INTEGER NOT NULL DEFAULT 0;

CREATE TABLE tags (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE article_tags (
    article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (article_id, tag_id)
);
